export * from "./analysts.js";

/**
 * Authentication tables, generated by the Better Auth CLI. Never edited by hand
 * — see CONTRIBUTING.md for how to regenerate them.
 *
 * Two conventions are broken here, knowingly, and it is worth writing down why
 * rather than leaving the next reader to wonder:
 *
 * - The table names are singular (`user`, `session`) where ours are plural.
 * - The timestamps are `timestamp` rather than `timestamptz`.
 *
 * Both are what the generator emits. The library reads and writes those columns
 * itself and treats them as UTC throughout, so the behaviour is right; only the
 * spelling differs. Editing the file to match our conventions would win a
 * cosmetic point and lose it again on the next regeneration, and a schema that
 * silently disagrees with the library that owns it is a much worse problem than
 * an inconsistent column type.
 */
export * from "./auth.js";

export * from "./common.js";
export * from "./decisions.js";
export * from "./digests.js";
export * from "./events.js";
export * from "./items.js";
export * from "./keys.js";
export * from "./logs.js";
export * from "./profiles.js";
export * from "./sources.js";
export * from "./tenancy.js";
